### ISSUE TITLE
I can't parse the string when there is double slash.

### ISSUE THREAD

**Issue by highdali** [timjansen/hanson#10]
I can't parse the string when there is double slash.

```js
SyntaxError: Unexpected token \ in JSON at position 210
    at JSON.parse (<anonymous>)
    at Object.parse (/Users/highdali/dev/book-review-moa/node_modules/hanson/hanson.js:76:17)
```

Input data was
```
["\uB2E8\uC21C\uD558\uB2E4. \","\uC778\uD130\uD30C\uD06C\uB3C4\uC11C","HelloET","20170321","http://book.interpark.com/blog/HelloET/4829812","\uC790\uC874\uAC10 \uC218\uC5C5\uC744 \uC77D\uACE0"]
```
Notice that there is backslash.

**Comment by timjansen** [comment]
Thanks, looks like it interprets it as comment. Will look into it.

**Comment by timjansen** [comment]
Sorry, I can't reproduce this. I created this JSFiddle to reproduce: https://jsfiddle.net/kLvbwgzt/1/
Doesn't seem to be the double slash. My guess would be the backslash at the end of the first string, HanSON won't touch it and passes it right to the JSON parser. Can you parse your string using JSON.parse()? It shouldn't have anything Hanson-specific.

**Comment by highdali** [comment]
`JSON.parse` can't parse the string. Sorry. Actually, the string was escaped already.
So [https://jsfiddle.net/highdali/c4dtzakn/](https://jsfiddle.net/highdali/c4dtzakn/)
