### ISSUE TITLE
Convert JSON to HanSON?

### ISSUE THREAD

**Issue by kentcdodds** [timjansen/hanson#4]
I have all my i18n translations written in HanSON. In part because we're using [messageformat.js](https://github.com/SlexAxton/messageformat.js) and having multi-lines is really nice. I'm combining all the i18n files for a certain language so I can distribute that to my translators as a single file. Is there an easy way to convert the JSON back to HanSON so my translators can benefit from the multi-line strings?

**Comment by timjansen** [comment]
Not yet. As every JSON file is also a HanSON file, you can create them, but
not in a human-friendly format. All comments etc will be lost.

Tim
